[#3] Get user language setting from bitzlato database
bitzlato/mailer pull request #10
Opened 2022-02-07 07:26 UTC by huryv45

2022-02-07 11:07 UTC, dapi commented on Gemfile.lock
> +  factory_bot_rails
я не против, но сам в последнее время пересел на fixtures, летает гораздо быстрее и проще

2022-02-07 11:08 UTC, dapi commented on app/models/user.rb
> +    @language ||=(bitzlato_profile&.lang&.presence || Mailer::App.config.default_language).to_sym
👍

2022-02-07 11:11 UTC, dapi requested changes

2022-02-07 11:11 UTC, dapi commented on app/models/user.rb
> +      .joins(:bitzlato_user)
Профиль бери лучше через модель bitzlato_user а запись в bitzlato_user нужно брать через сортировку. Потому что в базе могут быть пользователи с одинаковыми email-ми.

Пример:

https://github.com/bitzlato/whaler/blob/master/app/models/bitzlato_user.rb#L9-L23

2022-02-07 11:11 UTC, dapi commented on spec/rails_helper.rb
> +  puts e.to_s.strip
;)

2022-02-07 11:12 UTC, huryv45 commented on spec/rails_helper.rb
> +  puts e.to_s.strip
теперь это кажется можно убрать)

2022-02-07 11:14 UTC, huryv45 commented on app/models/user.rb
> +      .joins(:bitzlato_user)
Я тут сделал так, чтобы не делать два запроса в базу, а один через join. Сортировку я могу добавить и в этом варианте.

2022-02-07 11:15 UTC, huryv45 commented on Gemfile.lock
> +  factory_bot_rails
мне самому больше нравится `fixtures`, взял `factory_girl`, потому что в остальных проектах он, для единообразия больше. Давай переделаю на  `fixtures`?

2022-02-07 11:51 UTC, huryv45 commented on app/models/user.rb
> +      .joins(:bitzlato_user)
в общем, сделал вот так пока

2022-02-07 11:57 UTC, huryv45 commented on Gemfile.lock
> +  factory_bot_rails
в общем если план в будущем получать данные из `api`, то пока не трогаю, удалим в следующей итерации вместе с тестами моделей

2022-02-08 19:08 UTC, dapi commented on Gemfile.lock
> +  factory_bot_rails
я за fixtures

2022-02-08 19:10 UTC, dapi commented on app/models/user.rb
> +      .joins(:bitzlato_user)
ok!

2022-02-08 19:10 UTC, dapi approved these changes

2022-02-08 19:10 UTC, merged